apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: doan-backend
  name: doan-backend-deployment
  namespace: doan
spec:
  replicas: 2
  revisionHistoryLimit: 11
  selector:
    matchLabels:
      app: doan-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: doan-backend
      namespace: doan
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: doan-backend-configmap
          image: hainh0110/doan_backend:v1.0
          imagePullPolicy: Always
          name: doan-backend
          ports:
            - containerPort: 5000
              name: tcp
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: doan-backend-service
  namespace: doan
spec:
  ports:
    - name: tcp
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: doan-backend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: doan-backend-ingress
  namespace: doan
spec:
  ingressClassName: nginx
  rules:
    - host:
      http:
        paths:
          - backend:
              service:
                name: doan-backend-service
                port:
                  number: 5000
            path: /api
            pathType: Prefix